![University Logo](../Durham_University.svg)

# Introduction to NumPy

### Recap: Python Lists are a container for arbitrary data
 - We can create a list within square brackets: `[]`
 - Data is accessed by *index*, with the index starting at 0.

In [1]:
# Create a list with arbitrary data
my_list = [1, 'hello', True, 3.14]

# Accessing the data in the list
print("my_list[0] gives:", my_list[0])
print("my_list[1] gives:", my_list[1])
print("my_list[2] gives:", my_list[2])
print("my_list[3] gives:", my_list[3])

my_list[0] gives: 1
my_list[1] gives: hello
my_list[2] gives: True
my_list[3] gives: 3.14


#### You can count from the back with negative indices and get a slice using the colon `:`

In [2]:
# Copy of our list for reference
my_list = [1, 'hello', True, 3.14]

# Accessing the data in the list using negative index
print("my_list[-1] gives:",  my_list[-1])

# Slicing the list with indexes
print("my_list[1:3] gives:", my_list[1:3])  # Output: ['hello', True]


my_list[-1] gives: 3.14
my_list[1:3] gives: ['hello', True]


#### Lists are mutable: You can also modify the data by index

In [3]:
# Copy of our list for reference
my_list = [1, 'hello', True, 3.14]

# Modifying the data in the list
my_list[0] = 2
print("my_list after modification:", my_list)


my_list after modification: [2, 'hello', True, 3.14]


#### NumPy Arrays: Key Features

- Homogeneous: Only contain elements of the same/one data type.
- Fixed Size: Size cannot be changed once created.
- Memory-Efficient: More efficient than Python lists.
- Vectorized Operations: Perform operations on entire arrays at once.
- Multidimensional: Efficiently store and manipulate multi-dimensional data.
- Built-in Functions: Access to more mathematical operations and data manipulation.


#### We use NumPy by importing it

Typically we use the alias `np`, as projects tend to use NumPy a lot.

In [4]:
# Import NumPy module
import numpy as np

We can now access anything in numpy via `np.function`

In [5]:
# Use pi from NumPy
np.pi

3.141592653589793

#### We can create NumPy arrays from lists

In [6]:
# Create a list with floats from 1 to 5
my_list = [1.0, 2.0, 3.0, 4.0, 5.0]

# Convert into list
my_array = np.array(my_list)

# Display
my_array

array([1., 2., 3., 4., 5.])


The object type is a NumPy array. The type of contained data is dependent on the content and its type

In [7]:
# Check type and dtype
type(my_array), my_array.dtype

(numpy.ndarray, dtype('float64'))

Show that you can change the data type of array members to cast as floats instead

If a single string is present, everything will be cast into a string! In general, you should already input homogeneous lists

In [8]:
# Show casting in an array with a string
mixed_array = np.array([1, 2, 3, 4, 'hello'])
mixed_array.dtype, mixed_array[1]

(dtype('<U21'), np.str_('2'))

#### We can also read NumPy arrays from disk
For this first step we will use a set of bond lengths determined by X-ray diffraction. Let us have a look at the first lines of the file. 

In [9]:
data1_path = '../Data/presentation/bond_lengths.txt'

# Read data and display the first three lines
with open(data1_path, 'r') as fobj:
    lines = fobj.readlines()

for index, line in enumerate(lines):
    print(line.strip())
    if index > 3:
        break

Si  C   2.3048
Si  C   2.3093
Si  C   2.3465
Si  C   2.3929
Si  C   2.4052


Speaker Notes:

In this section explain: Opening files in Python. Control statements including the for loop, if statement and break. End on the statement that we have different data types!

## Let us now load the data using NumPy
Because we have different data types within each line in the file, we need to specify this. We load every column separately into a new variable

In [10]:
# Load data from txt, unpack and demonstrate data types
element1, element2, length = np.loadtxt(data1_path, dtype='U2,U2,float64', unpack=True)

Speaker Notes:

In this section: Revise element unpacking, and function arguments.

#### A quick look at what we loaded

In [11]:
# Do some slices through our array with start, stop and skip
element1[1:21:3], element2[1:21:3], length[1:21:3], length.dtype

(array(['Si', 'Si', 'C', 'C', 'C', 'C', 'C'], dtype='<U2'),
 array(['C', 'C', 'C', 'C', 'C', 'H', 'H'], dtype='<U2'),
 array([2.3093, 2.4052, 1.418 , 1.498 , 1.417 , 0.98  , 0.98  ]),
 dtype('float64'))

#### Let us have a look at the NumPy datatypes:

| Python| NumPy      | Numpy Short |
|-------|------------|-------------|
| float | float64    |   f8       |
| int   | int64      |   i8       |
| bool  | bool       |   b1        |
|complex| complex128 |   c16       |
| str   | str_       |  <U{n}       |

A list of all data types can be accessed with

In [12]:
np.sctypeDict.keys()

dict_keys(['bool', 'float16', 'float32', 'float64', 'longdouble', 'complex64', 'complex128', 'clongdouble', 'bytes_', 'str_', 'void', 'object_', 'datetime64', 'timedelta64', 'int8', 'byte', 'uint8', 'ubyte', 'int16', 'short', 'uint16', 'ushort', 'int32', 'intc', 'uint32', 'uintc', 'int64', 'long', 'uint64', 'ulong', 'longlong', 'ulonglong', 'intp', 'uintp', 'double', 'cdouble', 'single', 'csingle', 'half', 'bool_', 'int_', 'uint', 'float', 'complex', 'object', 'bytes', 'a', 'int', 'str', 'unicode', 'float128', 'complex256'])

#### Let us determine the mean bond length and its standard deviation
For this we can use NumPy's built-in functions. The full list can be found in the routines section of the [NumPy documentation](https://numpy.org/doc/stable/reference/routines.html). Specifically under *[statistics](https://numpy.org/doc/stable/reference/routines.statistics.html)*.

In [13]:
# Print mean and standard deviation of bond lengths
print(np.mean(length), np.std(length))

1.2838740112994351 0.4283874266912911


#### NumPy supports more sophisticated slicing than Python lists

In [14]:
# First five entries
length[:5]

array([2.3048, 2.3093, 2.3465, 2.3929, 2.4052])

In [15]:
# Slicing by indexing
indexes = [2, 3, 5, 7, 22]
length[indexes]

array([2.3465, 2.3929, 2.4275, 1.418 , 0.98  ])

#### We can create conditional selections with masks
A mask is an array of booleans that has the same size as the array we want to apply the mask to

In [16]:
# Create a mask array for values where element 1 is Si
mask = element1 == 'Si'
mask[2:8]

array([ True,  True,  True,  True, False, False])

In [17]:
# Apply our mask to length
length[mask]

array([2.3048, 2.3093, 2.3465, 2.3929, 2.4052, 2.4275, 2.3399, 2.3629,
       2.3749, 2.3862, 2.421 , 2.4355, 2.3087, 2.3309, 2.3411, 2.3701,
       2.4327, 2.4346])

Very often you would not store the mask in a variable

In [18]:
# Create the mask in line
length[element1 == 'Si']

array([2.3048, 2.3093, 2.3465, 2.3929, 2.4052, 2.4275, 2.3399, 2.3629,
       2.3749, 2.3862, 2.421 , 2.4355, 2.3087, 2.3309, 2.3411, 2.3701,
       2.4327, 2.4346])

#### Let us calculate means and standard deviations of different bond types
We will use the [logical operations](https://numpy.org/doc/stable/reference/routines.logic.html#logical-operations) for this purpose. `np.logical_and(arr1, arr2)` can be used to get the elementwise truth of "arr1 and arr2"

In [19]:
# np.logical_and can be used to get the elementwise truth of "arr1 and arr2"
# C-C bonds
cc_mask = np.logical_and(element1 == 'C', element2 == 'C')
np.mean(length[cc_mask]), np.std(length[cc_mask])

(np.float64(1.45835), np.float64(0.041565941586832855))

In [20]:
# Also get C-H bond lengths
ch_mask = np.logical_and(element1 == 'C', element2 == 'H')
np.mean(length[ch_mask]), np.std(length[ch_mask])

(np.float64(0.9800000000000004), np.float64(4.440892098500626e-16))

In [21]:
# Show & as shorthand
(element1 == 'C') & (element2 == 'H');

#### Numpy arrays can be multidimensional.

In [22]:
# Create a simple 2D array
mult = np.array([[1,2,3], [4,5,6], [7,8,9]])
mult

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
# Second row or third column
mult[1,:], mult[:,2]

(array([4, 5, 6]), array([3, 6, 9]))

In [24]:
# We can also use this for assignment
mult[1, :] = 0
mult

array([[1, 2, 3],
       [0, 0, 0],
       [7, 8, 9]])

Explain that this is a view of the original data and not a new object in memory

#### We can change the arrangement with reshape

In [25]:
# Create a linspace with size 12 in new var
numbers = np.linspace(0.0, 1.0, 12)
numbers

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

In [26]:
# Use reshape
np.reshape(numbers, (4,3))

array([[0.        , 0.09090909, 0.18181818],
       [0.27272727, 0.36363636, 0.45454545],
       [0.54545455, 0.63636364, 0.72727273],
       [0.81818182, 0.90909091, 1.        ]])

### Calculating with NumPy arrays and basic arithmetic
Let us load a new dataset. This time we skip the first column, which contains the atom type, and only load the coordinates. Because all loaded data columns have the same type, NumPy will automatically detect the correct type.

In [27]:
data_path2 = '../Data/presentation/molecule1.xyz'

# Load non-number columns from file (1,2,3)
coordinates = np.loadtxt(data_path2, usecols=(1,2,3))
coordinates.shape, coordinates.dtype

((51, 3), dtype('float64'))

Mathematical operations are calculated elementwise. Here we take the difference between two points

In [28]:
# Difference between arrays
coordinates[0] - coordinates[1]

array([-1.477886,  0.42672 , -2.043088])

The distance is the norm of that vector

In [29]:
# Calculate the length of that vector
np.linalg.norm(coordinates[0] - coordinates[1])

np.float64(2.5574294835126925)

#### Broadcasting an operation
We now want to calculate the distance of the first atom to all other atoms in the molecule

In [30]:
# Calculate the distance of all atoms to atom 1
diff = coordinates - coordinates[0]
print(diff.shape)
np.linalg.norm(diff, axis=-1)

(51, 3)


array([0.        , 2.55742948, 2.4054673 , 2.30937131, 2.39286202,
       2.54175625, 3.56497407, 3.64416286, 4.42093052, 3.70184382,
       3.37761395, 3.44725211, 3.51735778, 4.24267866, 3.36668177,
       3.54164164, 3.47282997, 4.20315821, 3.4025242 , 3.52993785,
       3.51178045, 4.25669029, 3.55654195, 3.61068653, 4.40948763,
       3.72256163, 2.30482234, 2.4273525 , 2.56677753, 2.51693889,
       2.34644284, 3.32366003, 3.46608293, 3.43992489, 4.17235977,
       3.4177005 , 3.40363197, 4.26257747, 3.66271932, 3.57797505,
       4.22595933, 4.17237041, 3.39843803, 3.54132471, 3.93582131,
       4.32393156, 3.43985706, 3.35887957, 3.44361902, 3.51622035,
       4.21207557])

Speaker notes: `diff` calculates the difference between first the coordinate, `coordinates[0]`, and all other coordinates. This gives us a list of vectors which we then want to calculate the length or `norm` of. To do this we have to `np.linalg.norm()` which `axis` to broadcast along.

Try different `axis` values:
* `axis=0` computes a function vertically
* `axis=-1` computes a function horizontally

# Linear Algebra
1D and 2D numerical arrays are often referred to as vectors and matrices, respectively. However, the rules of computation around these mathematical objects have subtle differences from numerical arrays.

In [31]:
# We define two arrays: A - a 3x3 matrix and B - a 3x1 vector
mat_A = np.array([[1, 0, 3], [-1, 2, 1], [-2, -2, 1]])
print(mat_A)
vec_A = np.array([[1], [0], [-1]])
print(vec_A)

print("Multiply matrix and vector = \n", mat_A @ vec_A)
print("Multiply 2D and 1D arrays = \n", mat_A * vec_A)

[[ 1  0  3]
 [-1  2  1]
 [-2 -2  1]]
[[ 1]
 [ 0]
 [-1]]
Multiply matrix and vector = 
 [[-2]
 [-2]
 [-3]]
Multiply 2D and 1D arrays = 
 [[ 1  0  3]
 [ 0  0  0]
 [ 2  2 -1]]


We can also use NumPy to compute matrix operations

In [32]:
# Calculate the determinant
mat_B = np.array([[1, 1], [-1, 1]])
print("mat_B =\n", mat_B)
print("det(mat_B) =", np.linalg.det(mat_B))

# Calculate eigenvalues and eigenvectors
mat_C = np.diag((2, 1))
eig_vals, eig_vecs = np.linalg.eig(mat_C)
print(mat_C)
print("Eigenvalues =", eig_vals)
print("Eigenvectors =\n", eig_vecs)

mat_B =
 [[ 1  1]
 [-1  1]]
det(mat_B) = 2.0
[[2 0]
 [0 1]]
Eigenvalues = [2. 1.]
Eigenvectors =
 [[1. 0.]
 [0. 1.]]


Returning to the coordinates data, we now want to apply an inversion matrix to all atomic positions.

In [33]:
# Create an inversion matrix
inv_mat = -1 * np.eye(3)
inv_mat

array([[-1., -0., -0.],
       [-0., -1., -0.],
       [-0., -0., -1.]])

In [34]:
# Use matmul with @
inv_mat @ coordinates[0]

array([-12.977027,  -2.90556 , -14.602081])

#### If we want to apply it to all coordinates we can use np.einsum
$C_{ik} = \sum\limits_j A_{ij} B_{jk}$

In [35]:
# Apply the inversion matrix using einsum
np.einsum('ij, ...j -> ...i', inv_mat, coordinates)

array([[-12.977027,  -2.90556 , -14.602081],
       [-14.454913,  -2.47884 , -16.645169],
       [-15.089983,  -3.30204 , -15.681198],
       [-14.334341,  -4.5066  , -15.565183],
       [-13.2189  ,  -4.40496 , -16.451158],
       [-13.305466,  -3.15336 , -17.110317],
       [-14.872292,  -1.09872 , -17.021242],
       [-14.077023,  -0.539314, -17.14586 ],
       [-15.384766,  -1.128019, -17.855966],
       [-15.429176,  -0.72004 , -16.309159],
       [-16.338744,  -2.97528 , -14.921884],
       [-16.337732,  -3.457331, -14.068454],
       [-16.375397,  -2.010952, -14.752293],
       [-17.120704,  -3.24455 , -15.447864],
       [-14.766341,  -5.74728 , -14.841933],
       [-13.981967,  -6.301336, -14.647097],
       [-15.207683,  -5.498968, -14.002951],
       [-15.391468,  -6.251456, -15.403326],
       [-12.202574,  -5.47428 , -16.694704],
       [-11.328352,  -5.062798, -16.857886],
       [-12.147624,  -6.057719, -15.90921 ],
       [-12.465876,  -6.003152, -17.476635],
       [-1

Speaker notes: `einsum` is a powerful function with lots of flexibility. In this case we are multiplying a matrix with indices `ij` by a vector with one index `j`. This function should return a vector with one index `i`, but we have a vector defined in each row of `coordinates` so we use the `...` notation to broadcast along these rows

# Summary and Key Takeaways

- **NumPy Arrays**: NumPy arrays are homogeneous, fixed-size, memory-efficient data structures that support vectorized operations and multi-dimensional data.

- **Array Operations**: NumPy provides a wide range of operations that can be performed on arrays, including arithmetic operations, reshaping, indexing, slicing, and statistical operations.

- **Broadcasting**: NumPy's broadcasting feature allows for arithmetic operations between arrays of different shapes.

- **Boolean Indexing**: NumPy arrays support boolean indexing, which can be used to filter data based on certain conditions.

- **Data Reading**: NumPy can be used to read data from files, enabling further data manipulation and analysis.

- **Statistical Measures**: We learned how to calculate mean, standard deviation, and other statistical measures using NumPy.

- **Advanced Operations**: We explored advanced operations like `np.einsum` which provides a way to compute multivariate operations on arrays.

Now we will move on to the exercises